<?php


namespace App\Controller;
use App\Controller\AppController;


class CommentsController extends AppController
{

    public function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $comments = $this->Comments->get(1);
        dd($comments);

    }
}
