<?php


namespace App\Controller;
use App\Controller\AppController;


class GenresController extends AppController
{

    public function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $genres = $this->Genres->get(1);
        dd($genres);

    }
}
